// List of 100+ tools, categories, SEO metadata
const TOOLS = [
  // --- Text Tools (1-20) ---
  { slug: 'word-counter', title: 'Word Counter', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-font', description: 'Count words, characters, sentences and paragraphs instantly.', keywords: 'word counter, character counter, sentence count' },
  { slug: 'case-converter', title: 'Case Converter', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-exchange-alt', description: 'Convert text between UPPERCASE, lowercase, Title Case, and more.', keywords: 'case converter, upper to lower, title case' },
  { slug: 'remove-duplicate-lines', title: 'Remove Duplicate Lines', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-clone', description: 'Clean your lists by removing all duplicate lines.', keywords: 'remove duplicates, clean list, deduplicate' },
  { slug: 'text-reverser', title: 'Text Reverser', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-backward', description: 'Flip your text backwards or reverse the order of lines.', keywords: 'reverse text, mirror text, reverse lines' },
  { slug: 'upsidedown-text', title: 'Upside Down Text', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-level-down-alt', description: 'Flip your text upside down for social media and fun.', keywords: 'upside down text, flip text, rotate text' },
  { slug: 'morse-code-translator', title: 'Morse Code Translator', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-ellipsis-h', description: 'Convert text to morse code and decode it back to text.', keywords: 'morse code, text to morse, morse decoder' },
  { slug: 'binary-to-text', title: 'Binary to Text', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-01', description: 'Convert binary code (0101) into readable text.', keywords: 'binary to text, decode binary' },
  { slug: 'text-to-binary', title: 'Text to Binary', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-01', description: 'Convert any text into its binary representation.', keywords: 'text to binary, encode binary' },
  { slug: 'remove-line-breaks', title: 'Remove Line Breaks', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-align-left', description: 'Convert multi-line text into a single paragraph by removing breaks.', keywords: 'remove line breaks, text cleaner' },
  { slug: 'slug-generator', title: 'URL Slug Generator', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-link', description: 'Convert text into SEO-friendly URL slugs.', keywords: 'slug generator, url slug, seo slug' },
  { slug: 'line-counter', title: 'Line Counter', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-list-ol', description: 'Count the number of lines in your text block.', keywords: 'line counter, count lines' },
  { slug: 'sort-text-lines', title: 'Sort Text Lines', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-sort-alpha-down', description: 'Sort lines of text alphabetically or numerically.', keywords: 'sort text, alphabetical sort, sort lines' },
  { slug: 'lorem-generator', title: 'Lorem Ipsum Generator', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-paragraph', description: 'Generate placeholder lorem ipsum text for layouts.', keywords: 'lorem ipsum, placeholder text' },
  { slug: 'text-to-image', title: 'Text to Image', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-image', description: 'Convert text snippets into high-quality images.', keywords: 'text to image, code snippet image' },
  { slug: 'markdown-to-html', title: 'Markdown to HTML', category: 'Text Tools', category_slug: 'text', icon: 'fab fa-markdown', description: 'Convert markdown syntax into clean HTML code.', keywords: 'markdown to html, md to html' },
  { slug: 'html-to-markdown', title: 'HTML to Markdown', category: 'Text Tools', category_slug: 'text', icon: 'fab fa-html5', description: 'Convert HTML source code back into simple Markdown.', keywords: 'html to markdown, html to md' },
  { slug: 'text-repeater', title: 'Text Repeater', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-redo', description: 'Repeat a text string as many times as you want.', keywords: 'text repeater, repeat string' },
  { slug: 'add-line-numbers', title: 'Add Line Numbers', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-list-ol', description: 'Add sequential line numbers to your text block.', keywords: 'add line numbers, line numbering' },
  { slug: 'text-replacer', title: 'Find & Replace', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-search-plus', description: 'Find and replace words or patterns in your text.', keywords: 'find and replace, text replace' },
  { slug: 'remove-white-spaces', title: 'Remove White Spaces', category: 'Text Tools', category_slug: 'text', icon: 'fas fa-eraser', description: 'Remove extra spaces, tabs, and indentation from text.', keywords: 'remove spaces, trim text' },

  // --- Developer Tools (21-45) ---
  { slug: 'json-formatter', title: 'JSON Formatter', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-code', description: 'Pretty-print and validate JSON instantly in your browser.', keywords: 'json formatter, json validate, beautify json' },
  { slug: 'base64-encoder', title: 'Base64 Encoder/Decoder', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-binary', description: 'Encode and decode text to and from Base64 format.', keywords: 'base64 encoder, decode base64, encode base64' },
  { slug: 'uuid-generator', title: 'UUID Generator', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-id-badge', description: 'Generate RFC4122 compliant UUIDv4 identifiers.', keywords: 'uuid generator, unique id, guid generator' },
  { slug: 'html-formatter', title: 'HTML Formatter', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-file-code', description: 'Beautify and format your HTML code for readability.', keywords: 'html formatter, beautify html' },
  { slug: 'css-formatter', title: 'CSS Formatter', category: 'Developer Tools', category_slug: 'developer', icon: 'fab fa-css3', description: 'Format and prettify your CSS stylesheets.', keywords: 'css formatter, beautify css' },
  { slug: 'js-formatter', title: 'JavaScript Formatter', category: 'Developer Tools', category_slug: 'developer', icon: 'fab fa-js', description: 'Format and beautify your JavaScript code snippets.', keywords: 'js formatter, beautify js' },
  { slug: 'xml-formatter', title: 'XML Formatter', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-file-excel', description: 'Format and validate your XML data instantly.', keywords: 'xml formatter, beautify xml' },
  { slug: 'sql-formatter', title: 'SQL Formatter', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-database', description: 'Pretty-print and format your SQL queries.', keywords: 'sql formatter, beautify sql' },
  { slug: 'yaml-to-json', title: 'YAML to JSON', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-file-alt', description: 'Convert YAML configuration files into JSON format.', keywords: 'yaml to json, yml to json' },
  { slug: 'json-to-yaml', title: 'JSON to YAML', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-file-code', description: 'Convert JSON data into clean YAML syntax.', keywords: 'json to yaml, json to yml' },
  { slug: 'json-to-csv', title: 'JSON to CSV', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-file-csv', description: 'Convert JSON arrays into downloadable CSV files.', keywords: 'json to csv, json to excel' },
  { slug: 'csv-to-json', title: 'CSV to JSON', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-file-csv', description: 'Convert CSV data into JSON arrays and objects.', keywords: 'csv to json, excel to json' },
  { slug: 'url-encoder-decoder', title: 'URL Encoder/Decoder', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-link', description: 'Safely encode or decode URL parameters.', keywords: 'url encode, url decode' },
  { slug: 'html-entities', title: 'HTML Entities', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-code', description: 'Encode or decode special characters to HTML entities.', keywords: 'html entities, encode html' },
  { slug: 'jwt-decoder', title: 'JWT Decoder', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-user-shield', description: 'Decode and inspect JSON Web Tokens (JWT) payload.', keywords: 'jwt decoder, inspect jwt' },
  { slug: 'crontab-generator', title: 'Cron Expression Generator', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-clock', description: 'Generate cron schedules for automated tasks.', keywords: 'cron generator, crontab, cron schedule' },
  { slug: 'regex-tester', title: 'Regex Tester', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-search', description: 'Test and validate your Regular Expressions.', keywords: 'regex tester, test regex' },
  { slug: 'css-gradient-generator', title: 'CSS Gradient Generator', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-palette', description: 'Create beautiful CSS gradients visually.', keywords: 'css gradient, gradient generator' },
  { slug: 'css-box-shadow', title: 'Box Shadow Generator', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-layer-group', description: 'Generate CSS box-shadow properties visually.', keywords: 'box shadow, css shadow' },
  { slug: 'css-border-radius', title: 'Border Radius Generator', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-vector-square', description: 'Create custom CSS border-radius shapes.', keywords: 'border radius, css rounded' },
  { slug: 'js-minifier', title: 'JS Minifier', category: 'Developer Tools', category_slug: 'developer', icon: 'fab fa-js-square', description: 'Compress and minify your JavaScript files.', keywords: 'js minifier, compress js' },
  { slug: 'css-minifier', title: 'CSS Minifier', category: 'Developer Tools', category_slug: 'developer', icon: 'fab fa-css3-alt', description: 'Compress and minify your CSS stylesheets.', keywords: 'css minifier, compress css' },
  { slug: 'html-minifier', title: 'HTML Minifier', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-file-code', description: 'Compress and minify your HTML code.', keywords: 'html minifier, compress html' },
  { slug: 'color-picker', title: 'Color Picker', category: 'Developer Tools', category_slug: 'developer', icon: 'fas fa-eye-dropper', description: 'Pick and convert colors between HEX, RGB, and HSL.', keywords: 'color picker, hex picker, rgb picker' },

  // --- Security Tools (46-60) ---
  { slug: 'password-generator', title: 'Password Generator', category: 'Security Tools', category_slug: 'security', icon: 'fas fa-key', description: 'Generate secure random passwords with one click.', keywords: 'password generator, random password, secure password' },
  { slug: 'md5-hash', title: 'MD5 Hash Generator', category: 'Security Tools', category_slug: 'security', icon: 'fas fa-fingerprint', description: 'Generate MD5 cryptographic hashes from any string.', keywords: 'md5 hash, generate md5' },
  { slug: 'sha1-hash', title: 'SHA1 Hash Generator', category: 'Security Tools', category_slug: 'security', icon: 'fas fa-fingerprint', description: 'Generate secure SHA1 hashes for your data.', keywords: 'sha1 hash, generate sha1' },
  { slug: 'sha256-hash', title: 'SHA256 Hash Generator', category: 'Security Tools', category_slug: 'security', icon: 'fas fa-shield-alt', description: 'Generate high-security SHA256 hashes.', keywords: 'sha256 hash, sha256 generator' },
  { slug: 'sha512-hash', title: 'SHA512 Hash Generator', category: 'Security Tools', category_slug: 'security', icon: 'fas fa-shield-alt', description: 'Generate ultra-secure SHA512 hashes.', keywords: 'sha512 hash, sha512 generator' },
  { slug: 'htaccess-generator', title: '.htaccess Generator', category: 'Security Tools', category_slug: 'security', icon: 'fas fa-server', description: 'Generate .htaccess rules for Apache servers.', keywords: 'htaccess generator, apache config' },
  { slug: 'password-strength', title: 'Password Strength Checker', category: 'Security Tools', category_slug: 'security', icon: 'fas fa-tasks', description: 'Check how strong and secure your password is.', keywords: 'password checker, password strength' },
  { slug: 'aes-encryption', title: 'AES Encryption/Decryption', category: 'Security Tools', category_slug: 'security', icon: 'fas fa-lock', description: 'Encrypt and decrypt text using AES standard.', keywords: 'aes encryption, secure text' },

  // --- Image Tools (61-80) ---
  { slug: 'image-compressor', title: 'Image Compressor', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-file-image', description: 'Compress images in browser to reduce file size.', keywords: 'image compressor, optimize image' },
  { slug: 'image-resizer', title: 'Image Resizer', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-expand-arrows-alt', description: 'Resize images by width and height instantly.', keywords: 'image resizer, resize image' },
  { slug: 'hex-to-rgb', title: 'HEX to RGB Converter', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-palette', description: 'Convert HEX color codes to RGB format.', keywords: 'hex to rgb, color converter' },
  { slug: 'rgb-to-hex', title: 'RGB to HEX Converter', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-palette', description: 'Convert RGB color values to HEX codes.', keywords: 'rgb to hex, color converter' },
  { slug: 'image-to-base64', title: 'Image to Base64', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-code', description: 'Convert images into Base64 data strings.', keywords: 'image to base64, data uri' },
  { slug: 'base64-to-image', title: 'Base64 to Image', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-image', description: 'Decode Base64 strings back into viewable images.', keywords: 'base64 to image, decode image' },
  { slug: 'svg-to-png', title: 'SVG to PNG Converter', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-file-export', description: 'Convert SVG vector files into PNG images.', keywords: 'svg to png, vector to image' },
  { slug: 'png-to-jpg', title: 'PNG to JPG Converter', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-exchange-alt', description: 'Convert PNG images into JPG format.', keywords: 'png to jpg, image converter' },
  { slug: 'jpg-to-png', title: 'JPG to PNG Converter', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-exchange-alt', description: 'Convert JPG images into PNG format.', keywords: 'jpg to png, image converter' },
  { slug: 'favicon-generator', title: 'Favicon Generator', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-icons', description: 'Create favicons for your website from images.', keywords: 'favicon generator, web icon' },
  { slug: 'image-cropper', title: 'Image Cropper', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-crop', description: 'Crop and trim your images visually.', keywords: 'crop image, image trim' },
  { slug: 'webp-to-jpg', title: 'WebP to JPG Converter', category: 'Image Tools', category_slug: 'image', icon: 'fas fa-file-image', description: 'Convert modern WebP images to JPG format.', keywords: 'webp to jpg, webp converter' },

  // --- Converters (81-100) ---
  { slug: 'unit-converter', title: 'Unit Converter', category: 'Converters', category_slug: 'converters', icon: 'fas fa-exchange-alt', description: 'Convert between length, weight, and temp units.', keywords: 'unit converter, length converter' },
  { slug: 'timestamp-converter', title: 'Unix Timestamp Converter', category: 'Converters', category_slug: 'converters', icon: 'fas fa-calendar-check', description: 'Convert Unix timestamps to human-readable dates.', keywords: 'unix timestamp, date converter' },
  { slug: 'roman-numerals', title: 'Roman Numerals Converter', category: 'Converters', category_slug: 'converters', icon: 'fas fa-hashtag', description: 'Convert numbers to Roman numerals and back.', keywords: 'roman numerals, number converter' },
  { slug: 'number-to-words', title: 'Number to Words', category: 'Converters', category_slug: 'converters', icon: 'fas fa-spell-check', description: 'Convert numbers into written words.', keywords: 'number to words, spell numbers' },
  { slug: 'binary-to-hex', title: 'Binary to Hex', category: 'Converters', category_slug: 'converters', icon: 'fas fa-01', description: 'Convert binary code into hexadecimal values.', keywords: 'binary to hex, hex converter' },
  { slug: 'hex-to-binary', title: 'Hex to Binary', category: 'Converters', category_slug: 'converters', icon: 'fas fa-01', description: 'Convert hexadecimal values into binary code.', keywords: 'hex to binary, binary converter' },
  { slug: 'decimal-to-binary', title: 'Decimal to Binary', category: 'Converters', category_slug: 'converters', icon: 'fas fa-01', description: 'Convert decimal numbers into binary strings.', keywords: 'decimal to binary' },
  { slug: 'binary-to-decimal', title: 'Binary to Decimal', category: 'Converters', category_slug: 'converters', icon: 'fas fa-01', description: 'Convert binary strings into decimal numbers.', keywords: 'binary to decimal' },
  { slug: 'time-converter', title: 'Time Converter', category: 'Converters', category_slug: 'converters', icon: 'fas fa-clock', description: 'Convert between hours, minutes, seconds, and more.', keywords: 'time converter, duration converter' },
  { slug: 'speed-converter', title: 'Speed Converter', category: 'Converters', category_slug: 'converters', icon: 'fas fa-tachometer-alt', description: 'Convert between km/h, mph, and knots.', keywords: 'speed converter, kmh to mph' },

  // --- Utility & Math (101-120) ---
  { slug: 'age-calculator', title: 'Age Calculator', category: 'Utility Tools', category_slug: 'utility', icon: 'fas fa-calendar-alt', description: 'Calculate exact age from date of birth.', keywords: 'age calculator, dob calculator' },
  { slug: 'percentage-calculator', title: 'Percentage Calculator', category: 'Utility Tools', category_slug: 'utility', icon: 'fas fa-percent', description: 'Calculate percentages, increases, and decreases.', keywords: 'percentage calculator, math tools' },
  { slug: 'bmi-calculator', title: 'BMI Calculator', category: 'Utility Tools', category_slug: 'utility', icon: 'fas fa-weight', description: 'Calculate your Body Mass Index (BMI) easily.', keywords: 'bmi calculator, health tools' },
  { slug: 'qr-code-generator', title: 'QR Code Generator', category: 'Generators', category_slug: 'generators', icon: 'fas fa-qrcode', description: 'Create custom QR codes for links and text.', keywords: 'qr code, create qr code' },
  { slug: 'barcode-generator', title: 'Barcode Generator', category: 'Generators', category_slug: 'generators', icon: 'fas fa-barcode', description: 'Generate standard barcodes for products.', keywords: 'barcode generator, create barcode' },
  { slug: 'random-name-generator', title: 'Random Name Generator', category: 'Generators', category_slug: 'generators', icon: 'fas fa-user-tag', description: 'Generate random names for characters or testing.', keywords: 'random name, name generator' },
  { slug: 'random-number-generator', title: 'Random Number Generator', category: 'Generators', category_slug: 'generators', icon: 'fas fa-random', description: 'Pick random numbers within any range.', keywords: 'random number, pick random' },
  { slug: 'dice-roller', title: 'Dice Roller', category: 'Generators', category_slug: 'generators', icon: 'fas fa-dice', description: 'Roll virtual dice for games and decisions.', keywords: 'dice roller, roll dice' },
  { slug: 'flip-a-coin', title: 'Flip a Coin', category: 'Generators', category_slug: 'generators', icon: 'fas fa-coins', description: 'Heads or Tails? Flip a virtual coin instantly.', keywords: 'flip a coin, coin toss' },
  { slug: 'stopwatch', title: 'Stopwatch', category: 'Utility Tools', category_slug: 'utility', icon: 'fas fa-stopwatch', description: 'A precise online stopwatch with lap timing.', keywords: 'stopwatch, timer' },
  { slug: 'countdown-timer', title: 'Countdown Timer', category: 'Utility Tools', category_slug: 'utility', icon: 'fas fa-hourglass-start', description: 'Set a countdown timer for any duration.', keywords: 'countdown timer, alert' },
  { slug: 'metronome', title: 'Metronome', category: 'Utility Tools', category_slug: 'utility', icon: 'fas fa-drum', description: 'Keep the beat with our online metronome tool.', keywords: 'metronome, music tools' },
  { slug: 'screen-resolution', title: 'Screen Resolution Detector', category: 'Utility Tools', category_slug: 'utility', icon: 'fas fa-desktop', description: 'Detect your current screen resolution and window size.', keywords: 'screen resolution, window size' },
  { slug: 'my-ip', title: 'My IP Address', category: 'Utility Tools', category_slug: 'utility', icon: 'fas fa-network-wired', description: 'Find out your current public IP address.', keywords: 'my ip, what is my ip' },
  { slug: 'browser-info', title: 'Browser Info', category: 'Utility Tools', category_slug: 'utility', icon: 'fas fa-info-circle', description: 'Detect your browser, version, and OS details.', keywords: 'browser info, detect browser' }
];

const CATEGORIES = [
  { name: 'Text Tools', slug: 'text' },
  { name: 'Image Tools', slug: 'image' },
  { name: 'Developer Tools', slug: 'developer' },
  { name: 'Converters', slug: 'converters' },
  { name: 'Generators', slug: 'generators' },
  { name: 'Security Tools', slug: 'security' },
  { name: 'Utility Tools', slug: 'utility' }
];
